name: scribble
description: Scribble is a lightweight library for freehand drawing in Flutter
  supporting pressure, variable line width and more!
version: 0.9.1
repository: https://github.com/timcreatedit/scribble
issue_tracker: https://github.com/timcreatedit/scribble/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  perfect_freehand: ^2.3.2
  value_notifier_tools: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lintervention: ^0.1.1
  melos: ^5.2.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true