name: simpli
description: Polyline simplification algorithms, made simple! Sporting exciting algorithms such as Ramer-Douglas-Peucker and Visvalingam.
version: 0.1.1+1
repository: https://github.com/timcreatedit/scribble/tree/main/packages/simpli
homepage: https://whynotmake.it


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ">=1.0.0 <2.0.0"
  meta: ">= 1.0.0 <2.0.0"
  
dev_dependencies:
  lintervention: ^0.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
  
